#!/usr/bin/env python3
# This file is placed in the Public Domain


"build all"


import os


SILENT = 1


def popen(txt):
    for line in os.popen(txt).readlines():
        if not SILENT:
            print(line.rstrip())


popen("sbin/wipe")
popen("sbin/check")
popen("sbin/build")
popen("sbin/lint")
popen("sbin/test")
popen("sbin/env")
