#!/usr/bin/env python3
# This file is placed in the Public Domain.


"cleanup"


import os


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line)


popen("rm -fR build dist MANIFEST *~ .op opd.egg-info __pycache__ .pytest_cache")
popen("rm -fR bin/*~")
popen("rm -fR sbin/*~")
popen("rm -fR .test test/*~ test/__pycache__")
popen("rm -fR opd/*~ opd/__pycache__")
popen("rm -fR mod/*~ mod/__pycache__")
