#!/usr/bin/env python3


"run pytest"


import os
import sys


os.environ["PYTHONPATH"] = "."


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())


popen("python3 -m pytest")
